# Hooks that run on each commit
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
# Python code formatter
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args: ["--line-length=79"]
# PEP8 sorts python import statements alphabetically
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
# Checks code compliance according to PEP8
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
# Checks types
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.7.0"
    hooks:
    - id: mypy
